on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - src/**
      - lse-api/**
      - xmake.lua
  push:
    paths:
      - .github/workflows/build.yml
      - src/**
      - lse-api/**
      - xmake.lua
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target_type:
          - server
        mode:
          # - debug
          - release
        test:
          - true
          - false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: xmake-io/github-action-setup-xmake@v1
        # with:
        #   xmake-version: branch@master

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - uses: microsoft/setup-msbuild@v2

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m ${{ matrix.mode }} -p windows -v -y --target_type=${{ matrix.target_type }} --test=${{ matrix.test }}

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: levifakeplayer-${{ matrix.target_type }}-${{ matrix.mode }}${{ matrix.test == true && '-test' || '' }}-windows-x64-${{ github.sha }}
          path: |
            bin/
